default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
        -   id: check-merge-conflict
        -   id: check-added-large-files
            args: ['--maxkb=30000']
        -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
-   repo: local
    hooks:
    -   id: autoflake
        name: autoflake
        description: remove unused imports
        entry: autoflake
        args: [
            "--in-place",
            "--remove-unused-variables"
        ]
        language: python
        language_version: python3.8
        types: [python]
        require_serial: true
        additional_dependencies: [autoflake]
    -   id: isort
        name: isort
        description: Automatically sort imports.
        entry: isort
        args: [
            "--profile", "black"
        ]
        language: python
        language_version: python3.8
        types: [python]
        require_serial: true
        additional_dependencies: [isort]
