[tool.poetry]
name = "fpl-stats-streamlit"
version = "0.1.0"
description = ""
authors = ["Prathamesh Sarang <prthamesh@hey.com>"]

[tool.poetry.dependencies]
python = "^3.8.2"
click = "^7.1.2"
streamlit = "^0.69.2"
loguru = "^0.5.3"
pandas = "^1.1.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
